site_name: DevOps Team Portal
site_description: Internal documentation for secure access, deployments, and monitoring
site_author: Your Team Name
site_url: https://yourcompany.github.io/devops-portal/

theme:
  name: material
  language: en
  logo: assets/images/logo.png         # Optional: logo for branding
  favicon: assets/images/favicon.ico   # Optional: company favicon
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - header.autohide
      - toc.toggle  
  extra_javascript:
    - assets/scripts/toc-toggle.js
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Fira Code
  icon:
    logo: material/cloud-outline  # Replace with your preferred icon

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quickstart.md
    - FAQ: faq.md
    - Contact: contact.md
  - DevOps Portal:
    - SCM Access & Monitoring Guide: devops/scm-access-monitoring-guide.md
    # - CI/CD Standards: devops/cicd-standards.md
    # - Terraform Guidelines: devops/terraform.md

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys

plugins:
  - search
  # - git-revision-date-localized  # Shows "Last updated" info
  # - minify                        # Reduces final site size
  # - awesome-pages                 # Auto nav from folder structure

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Maersk-Global/scm-central-gitops
    - icon: fontawesome/brands/slack
      link: https://slack.com/your-team
  generator: false  # Hides "Powered by MkDocs" in footer

extra_css:
  - assets/styles/custom.css        # Optional: internal branding

extra_javascript:
  - assets/scripts/custom.js        # Optional: behavior or interactivity
