name: Deploy DevOps Portal to GitHub Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: write  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Dependencies
        run: |
          pip install mkdocs-material
          pip install \
            pymdown-extensions \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-minify-plugin \
            mkdocs-awesome-pages-plugin

      - name: Build Site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
